"""Add status to application

Revision ID: 9f72ab86d53f
Revises: 98bb3bfaaec1
Create Date: 2025-04-26 19:37:15.709976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f72ab86d53f'
down_revision = '98bb3bfaaec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
