"""إضافة experience إلى نموذج الباحث عن عمل

Revision ID: 5ade5c47b87e
Revises: b98075c38984
Create Date: 2025-03-06 02:49:08.930944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ade5c47b87e'
down_revision = 'b98075c38984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.String(length=10), nullable=True))
        batch_op.drop_column('experience_years')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_years', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('experience')

    # ### end Alembic commands ###
