"""إضافة experience_years إلى نموذج الباحث عن عمل

Revision ID: 678ac18d6b50
Revises: 5ade5c47b87e
Create Date: 2025-03-06 02:51:12.808342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678ac18d6b50'
down_revision = '5ade5c47b87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_years', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('experience_years')

    # ### end Alembic commands ###
