"""إضافة إعدادات الإشعارات والمظهر للمستخدم

Revision ID: 7144d429d5c0
Revises: ee42e593faac
Create Date: 2025-03-04 06:13:30.551872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7144d429d5c0'
down_revision = 'ee42e593faac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.String(length=10), nullable=True))
        batch_op.drop_constraint('uq_user_phone', type_='unique')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(length=250), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_user_phone', ['phone'])
        batch_op.drop_column('theme')
        batch_op.drop_column('notifications_enabled')

    # ### end Alembic commands ###
