"""Fixed models

Revision ID: 7fe9dc953929
Revises: 678ac18d6b50
Create Date: 2025-03-07 23:45:38.850896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe9dc953929'
down_revision = '678ac18d6b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
