"""إضافة العلاقة بين الوظائف والمتقدمين

Revision ID: b583e40ca231
Revises: b97afb1ea5cc
Create Date: 2025-03-04 17:57:37.705245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b583e40ca231'
down_revision = 'b97afb1ea5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_column('qr_code')

    # ### end Alembic commands ###
