"""إضافة حقول الرغبات للباحث عن عمل

Revision ID: ccaa02aa909b
Revises: b583e40ca231
Create Date: 2025-03-06 02:22:01.901123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccaa02aa909b'
down_revision = 'b583e40ca231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('desired_role', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('preferred_location', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferred_location')
        batch_op.drop_column('languages')
        batch_op.drop_column('desired_role')
        batch_op.drop_column('experience')

    # ### end Alembic commands ###
