"""add profile_picture and other fields to User

Revision ID: a525dac35540
Revises: 2460785a0e80
Create Date: 2025-04-18 14:14:35.480660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a525dac35540'
down_revision = '2460785a0e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('applied_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('highest_education', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('university_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('graduation_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('field_of_study', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('experience_years', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('previous_jobs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('technical_skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('soft_skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('preferred_salary', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('job_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('willing_to_relocate', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('available_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('languages', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('language_proficiency', sa.String(length=255), nullable=True))
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('language_proficiency')
        batch_op.drop_column('languages')
        batch_op.drop_column('available_start_date')
        batch_op.drop_column('willing_to_relocate')
        batch_op.drop_column('job_type')
        batch_op.drop_column('preferred_salary')
        batch_op.drop_column('preferred_location')
        batch_op.drop_column('soft_skills')
        batch_op.drop_column('technical_skills')
        batch_op.drop_column('skills')
        batch_op.drop_column('certifications')
        batch_op.drop_column('industry')
        batch_op.drop_column('previous_jobs')
        batch_op.drop_column('experience_years')
        batch_op.drop_column('field_of_study')
        batch_op.drop_column('graduation_year')
        batch_op.drop_column('university_name')
        batch_op.drop_column('highest_education')
        batch_op.drop_column('gender')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('profile_picture')

    op.drop_table('application')
    # ### end Alembic commands ###
